CREATE TABLE IF NOT EXISTS ADDRESS (
    ID INT NOT NULL AUTO_INCREMENT,
    add1 VARCHAR(100) NULL DEFAULT NULL ,
    add2 VARCHAR(100) NULL DEFAULT NULL ,
    city VARCHAR(50) NULL DEFAULT NULL ,
    state VARCHAR(50) NULL DEFAULT NULL ,
    pin VARCHAR(10) NULL DEFAULT NULL ,
    PRIMARY KEY (ID)
)